version: '2'
volumes:
    # This RAM drive is for raspicam to place a constant stream of images while not
    # burning out MicroSD card, pending motion detection and move to image-ready.
    image-temp:
        driver_opts:
        type: tmpfs
        device: tmpfs
        # 128MB (in bytes)
        size: 134217728
    # Images are stored here when motion is detected, ready for upload when possible.
    image-ready:
services:
    raspicam-manager:
        build: ./raspicam-manager
        volumes:
            - 'image-temp:/image-temp'