version: '2'
volumes:
  # This RAM drive is for raspicam to place a constant stream of images while not
  # burning out MicroSD card, pending motion detection and move to image-ready.
  image-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      # 64MB (in bytes)
      size: 67108864
  # Images are stored here when motion is detected, ready for upload when possible.
  image-ready:
services:
  security-camera:
    build: ./security-camera
    volumes:
      - 'image-temp:/image-temp'
      - 'image-ready:/image-ready'
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      - IMAGE_WIDTH
      - IMAGE_HEIGHT
      - IMAGE_QUALITY
      - IMAGE_ROTATION
      - THUMB_WIDTH
      - THUMB_HEIGHT
      - AWS_ENDPOINT
      - AWS_PRIVATE_CERT
      - AWS_ROOT_CERT
      - AWS_THING_CERT
      - AWS_REGION
      - AWS_IMAGE_BUCKET
      - MOTION_SENSITIVITY
      - MOTION_HOTSPOTS
      - DB_RECORD_TTL
