name: Code Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Camera - Install with Node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Camera - Install Dependencies
      run: npm i --prefix camera/security-camera
    - name: Camera - Run Tests
      run: npm run test --prefix camera/security-camera
    - name: Camera - Setup Code Climate cc-test-reporter
      # TODO: Having trouble getting cc-test-reporter to work with subdirectories (--prefix and --prefix-path)
      # This is a temporary solution to cover camera only. Expand on it.
      working-directory: ./camera/security-camera
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Camera - Format Test Coverage Results
      working-directory: ./camera/security-camera
      run: ./cc-test-reporter format-coverage -t lcov -o ./coverage/codeclimate.camera.json ./coverage/lcov.info
    - name: Upload Coverage Results To Code Climate
      working-directory: ./camera/security-camera
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      run: |
        ./cc-test-reporter sum-coverage ./coverage/codeclimate.*.json -p 1 -o ./coverage/codeclimate.total.json
        ./cc-test-reporter upload-coverage -i ./coverage/codeclimate.total.json
